-- MySQL Script generated by MySQL Workbench
-- Mon Jan 13 13:59:53 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Entreprise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Entreprise` (
  `idEntreprise` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `adresse` VARCHAR(45) NOT NULL,
  `dateInscription` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEntreprise`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Personne`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Personne` (
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `statut` VARCHAR(45) NOT NULL,
  `adresse mail` VARCHAR(45) NOT NULL,
  `N°Inscription` INT NOT NULL AUTO_INCREMENT,
  `Mot de passe` VARCHAR(45) NOT NULL,
  `Poid` INT NOT NULL,
  `Taille` INT NOT NULL,
  `âge` INT NOT NULL,
  `Entreprise_idEntreprise` INT NOT NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`N°Inscription`),
  INDEX `fk_Personne_Entreprise1_idx` (`Entreprise_idEntreprise` ASC) VISIBLE,
  CONSTRAINT `fk_Personne_Entreprise1`
    FOREIGN KEY (`Entreprise_idEntreprise`)
    REFERENCES `mydb`.`Entreprise` (`idEntreprise`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`test` (
  `date` DATE NOT NULL,
  `n°test` INT NOT NULL AUTO_INCREMENT,
  `Personne_N°Inscription` INT NOT NULL,
  PRIMARY KEY (`n°test`),
  INDEX `fk_test_Personne_idx` (`Personne_N°Inscription` ASC) VISIBLE,
  CONSTRAINT `fk_test_Personne`
    FOREIGN KEY (`Personne_N°Inscription`)
    REFERENCES `mydb`.`Personne` (`N°Inscription`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Appareil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Appareil` (
  `idAppareil` INT NOT NULL AUTO_INCREMENT,
  `NumCarte` INT NULL,
  `test_n°test` INT NOT NULL,
  PRIMARY KEY (`idAppareil`),
  INDEX `fk_Appareil_test1_idx` (`test_n°test` ASC) VISIBLE,
  CONSTRAINT `fk_Appareil_test1`
    FOREIGN KEY (`test_n°test`)
    REFERENCES `mydb`.`test` (`n°test`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Capteur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Capteur` (
  `n°capteur` INT NOT NULL AUTO_INCREMENT,
  `seuilMin` INT NOT NULL,
  `seuilMax` INT NOT NULL,
  `UniteMesure` VARCHAR(45) NOT NULL,
  `modeleCapteur` VARCHAR(45) NOT NULL,
  `Appareil_idAppareil` INT NOT NULL,
  PRIMARY KEY (`n°capteur`),
  INDEX `fk_Capteur_Appareil1_idx` (`Appareil_idAppareil` ASC) VISIBLE,
  CONSTRAINT `fk_Capteur_Appareil1`
    FOREIGN KEY (`Appareil_idAppareil`)
    REFERENCES `mydb`.`Appareil` (`idAppareil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mesures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mesures` (
  `Valeurs` INT NOT NULL,
  `Temps` DATETIME NOT NULL,
  `Capteur_n°capteur` INT NOT NULL,
  `Capteur_test_n°test` INT NOT NULL,
  PRIMARY KEY (`Temps`),
  INDEX `fk_Mesures_Capteur1_idx` (`Capteur_n°capteur` ASC, `Capteur_test_n°test` ASC) VISIBLE,
  CONSTRAINT `fk_Mesures_Capteur1`
    FOREIGN KEY (`Capteur_n°capteur`)
    REFERENCES `mydb`.`Capteur` (`n°capteur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`topic` (
  `idTopic` INT NOT NULL AUTO_INCREMENT,
  `contenu topic` MULTILINESTRING NOT NULL,
  PRIMARY KEY (`idTopic`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Commentaires`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Commentaires` (
  `idCommentaires` INT NOT NULL AUTO_INCREMENT,
  `contenuCommentaire` MULTILINESTRING NOT NULL,
  `topic_idTopic` INT NOT NULL,
  PRIMARY KEY (`idCommentaires`),
  INDEX `fk_Commentaires_topic1_idx` (`topic_idTopic` ASC) VISIBLE,
  CONSTRAINT `fk_Commentaires_topic1`
    FOREIGN KEY (`topic_idTopic`)
    REFERENCES `mydb`.`topic` (`idTopic`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`typesCapteurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`typesCapteurs` (
  `idtypesCapteurs` INT NOT NULL AUTO_INCREMENT,
  `typeCapteur` VARCHAR(45) NOT NULL,
  `Capteur_n°capteur` INT NOT NULL,
  PRIMARY KEY (`idtypesCapteurs`),
  INDEX `fk_typesCapteurs_Capteur1_idx` (`Capteur_n°capteur` ASC) VISIBLE,
  CONSTRAINT `fk_typesCapteurs_Capteur1`
    FOREIGN KEY (`Capteur_n°capteur`)
    REFERENCES `mydb`.`Capteur` (`n°capteur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pageWeb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pageWeb` (
  `numéroPageWeb` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`numéroPageWeb`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`paragrapheModifiable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`paragrapheModifiable` (
  `idparagrapheModifiable` INT NOT NULL AUTO_INCREMENT,
  `contenu` MULTILINESTRING NOT NULL,
  `pageWeb_numéroPageWeb` INT NOT NULL,
  PRIMARY KEY (`idparagrapheModifiable`),
  INDEX `fk_paragrapheModifiable_pageWeb1_idx` (`pageWeb_numéroPageWeb` ASC) VISIBLE,
  CONSTRAINT `fk_paragrapheModifiable_pageWeb1`
    FOREIGN KEY (`pageWeb_numéroPageWeb`)
    REFERENCES `mydb`.`pageWeb` (`numéroPageWeb`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`permisConduire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`permisConduire` (
  `idNationalPermisConduire` INT NOT NULL,
  `typePermis` VARCHAR(45) NOT NULL,
  `Personne_N°Inscription` INT NOT NULL,
  PRIMARY KEY (`idNationalPermisConduire`),
  INDEX `fk_permisConduire_Personne1_idx` (`Personne_N°Inscription` ASC) VISIBLE,
  CONSTRAINT `fk_permisConduire_Personne1`
    FOREIGN KEY (`Personne_N°Inscription`)
    REFERENCES `mydb`.`Personne` (`N°Inscription`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`typePermisConduire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`typePermisConduire` (
  `typ` INT NOT NULL,
  PRIMARY KEY (`typ`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`adminForum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`adminForum` (
  `idadminForum` INT NOT NULL AUTO_INCREMENT,
  `adresseMail` VARCHAR(45) NOT NULL,
  `MotDePasse` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idadminForum`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
